[#common_usage]
= Usage

The workday calculation methods are accessible through CalculatorCoreAction class.
The available methods are explained below.

== calculateWorkday() method

The calculateWorkday() method is used for querying the n-th workday before or after a given date.

Input:

* LocalDate startDate: must be between years 1 and 2100

* int numberOfWorkdays: positive or negative integer, can't be zero

Output:

* LocalDate: startDate + numberOfWorkdays

Exceptions:

* BusinessException on invalid input parameters

Example:

  Given we have in cache:
  (2020, 5, 15) - workday
  (2020, 5, 16) - not workday
  (2020, 5, 17) - not workday
  (2020, 5, 18) - workday
  (2020, 5, 19) - workday
  (2020, 5, 20) - workday
  Then:
  calculateWorkday(LocalDate.of(2020, 5, 15), 3) = (2020, 5, 20)

== calculateWorkdayList() method

The calculateWorkdayList() method is used for querying a list of workdays between two dates.

Input:

* LocalDate startDate: must be between years 1 and 2100

* LocalDate endDate: must be between years 1 and 2100, can't be earlier than startDate

Output:

* List<LocalDate>: workday dates between startDate and endDate (both inclusive)

Exceptions:

* BusinessException on invalid input parameters

Example:

  Given we have in cache:
  (2020, 5, 9) - not workday
  (2020, 5, 10) - not workday
  (2020, 5, 11) - workday
  (2020, 5, 12) - workday
  (2020, 5, 13) - workday
  (2020, 5, 14) - workday
  (2020, 5, 15) - workday
  Then:
  calculateWorkdayList(LocalDate.of(2020, 5, 9), LocalDate.of(2020, 5, 15)) = [
  (2020, 5, 11), (2020, 5, 12), (2020, 5, 13), (2020, 5, 14), (2020, 5, 15)]

== isGuaranteedResultOfCalculateWorkday() method (from v1.2.0)
Returns whether the result of the given calculateWorkday() method is guaranteed.

Input:

* LocalDate startDate: must be between years 1 and 2100

* int numberOfWorkdays: positive or negative integer, can't be zero

Output:

* boolean: returns true if the processing only affects the years of the source file, otherwise it returns false

Exceptions:

* BusinessException on invalid input parameters

Example:

  Given source file contains data only year 2020.
  Then:
  isGuaranteedResultOfCalculateWorkday(LocalDate.of(2020, 12, 31), 1) = false


== isGuaranteedResultOfCalculateWorkdayList() method (from v1.2.0)
Returns whether the result of the given calculateWorkdayList() method is guaranteed.

Input:

* LocalDate startDate: must be between years 1 and 2100

* LocalDate endDate: must be between years 1 and 2100, can't be earlier than startDate

Output:

* boolean: returns true if the processing only affects the years of the source file, otherwise it returns false

Exceptions:

* BusinessException on invalid input parameters

Example:

  Given source file contains data only year 2020.
  Then:
  isGuaranteedResultOfCalculateWorkdayList(LocalDate.of(2020, 12, 1), LocalDate.of(2021, 1, 1)) = false
